export const dummyColumnNames = [
  "Desserts",
  "Calories",
  "Fat (g)",
  "Carbs (g)",
  "Protein (g)",
  "Dupa (g)",
  "Harry",
  "Dupper",
  "Nanana",
];

export const dummyTableRows = [
  {
    rowName: "Frozen yoghurt",
    calories: 159,
    fat: "6.0",
    carbs: 24,
    protein: 4.0,
    dupa: 6,
    harry: "Harry1",
    dupper: "Dupper1",
    nanana: "nanana1",
  },
  {
    rowName: "Ice cream sandwich",
    calories: 237,
    fat: 9.0,
    carbs: 37,
    protein: 4.3,
    dupa: 6,
    harry: "Harry2",
    dupper: "Dupper2",
    nanana: "nanana2",
  },
  {
    rowName: "Eclair",
    calories: 262,
    fat: 16.0,
    carbs: 24,
    protein: 6.0,
    dupa: 6,
    harry: "Harry3",
    dupper: "Dupper3",
    nanana: "nanana3",
  },
  {
    rowName: "Cupcake",
    calories: 305,
    fat: 3.7,
    carbs: 67,
    protein: 4.3,
    dupa: 6,
    harry: "Harry4",
    dupper: "Dupper4",
    nanana: "nanana4",
  },
  {
    rowName: "Gingerbread",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
    harry: "Harry5",
    dupper: "Dupper5",
    nanana: "nanana5",
  },
  {
    rowName: "Honeycomb",
    calories: 408,
    fat: 3.2,
    carbs: 87,
    protein: 6.5,
    dupa: 6,
    harry: "Harry6",
    dupper: "Dupper6",
    nanana: "nanana6",
  },
  {
    rowName: "Ice cream sandwich",
    calories: 237,
    fat: 9,
    carbs: 37,
    protein: 4.3,
    dupa: 6,
    harry: "Harry7",
    dupper: "Dupper7",
    nanana: "nanana7",
  },
  {
    rowName: "Jelly Bean",
    calories: 375,
    fat: 0,
    carbs: 94,
    protein: 0,
    dupa: 6,
    harry: "Harry8",
    dupper: "Dupper8",
    nanana: "nanana8",
  },
  {
    rowName: "KitKat",
    calories: 518,
    fat: 26,
    carbs: 65,
    protein: 7,
    dupa: 6,
    harry: "Harry9",
    dupper: "Dupper9",
    nanana: "nanana9",
  },
  {
    rowName: "Lollipop",
    calories: 392,
    fat: 0.2,
    carbs: 98,
    protein: 0,
    dupa: 6,
    harry: "Harry10",
    dupper: "Dupper10",
    nanana: "nanana10",
  },
  {
    rowName: "Marshmallow",
    calories: 318,
    fat: 0,
    carbs: 81,
    protein: 2,
    dupa: 6,
    harry: "Harry11",
    dupper: "Dupper11",
    nanana: "nanana11",
  },
  {
    rowName: "Nougat",
    calories: 360,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
    harry: "Harry12",
    dupper: "Dupper12",
    nanana: "nanana12",
  },
  {
    rowName: "Oreo",
    calories: 437,
    fat: 18,
    carbs: 63,
    protein: 4,
    dupa: 6,
    harry: "Harry13",
    dupper: "Dupper13",
    nanana: "nanana13",
  },
];
