export const dummyColumnNames = [
  "Calories",
  "Fat (g)",
  "Carbs (g)",
  "Protein (g)",
  "Dupa (g)",
];

export const dummyTableRows = [
  {
    rowName: "Frozen yoghurt",
    calories: 159,
    fat: 6.0,
    carbs: 24,
    protein: 4.0,
    dupa: 6,
  },
  {
    rowName: "Ice cream sandwich",
    calories: 237,
    fat: 9.0,
    carbs: 37,
    protein: 4.3,
    dupa: 6,
  },
  {
    rowName: "Eclair",
    calories: 262,
    fat: 16.0,
    carbs: 24,
    protein: 6.0,
    dupa: 6,
  },
  {
    rowName: "Cupcake",
    calories: 305,
    fat: 3.7,
    carbs: 67,
    protein: 4.3,
    dupa: 6,
  },
  {
    rowName: "Gingerbread",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
  {
    rowName: "Honeycomb",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
  {
    rowName: "Ice cream sandwich",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
  {
    rowName: "Jelly Bean",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
  {
    rowName: "KitKat",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
  {
    rowName: "Lollipop",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
  {
    rowName: "Marshmallow",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
  {
    rowName: "Nougat",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
  {
    rowName: "Oreo",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
    dupa: 6,
  },
];
